### ISSUE TITLE
Use local storage to remember decisions

### ISSUE THREAD

**Issue by snicoll** [spring-io/bomr#6]
As a complement of #4, it would be nice to remember decisions that were made for a given line and a given dependency. 

Consider the following use case: `bomr` runs on a project for which 5 dependencies have to be ignored because they can't be upgraded at the moment. If we run `bomr` right after (i.e. considering the state of things is the same), `bomr` will ask the user again for those 5 dependencies.

If a dependency is excluded for a project, a version and a list of versions, it should be automatically skipped if the tool runs again with the same state.

**Comment by snicoll** [comment]
It would also be nice that we're able to store decisions on specific dependencies. For instance, if the upgrade policy of a dependency is conditional on how it's being used in a project, we should have a way to add an informative message to let the user know. 

This would help us double check that the dependency upgrade has been blessed.

**Comment by jabrena** [comment]
Here, one idea: 
https://www.thoughtworks.com/radar/techniques/lightweight-architecture-decision-records

**Comment by wilkinsona** [comment]
Hopefully 
https://github.com/spring-io/bomr/commit/9cfb4bbc8bedab152ff5ea04a00ef6f6dbfabb8a gives us what we need here.
